[prune]
  non-go = true
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.12.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "9.0.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/urfave/cli.v2"

[[constraint]]
  name = "github.com/containerum/kube-client"
  version = "0.23.33"

[[constraint]]
  name = "github.com/globalsign/mgo"
  version = "r2018.06.15"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"
