tags:
  db: true
  platformdb: false

replicaCount: 1

image:
  repository: containerum/kube-events
  tag: v1.0.0
  pullPolicy: IfNotPresent
  secret:

rbac:
  serviceAccountName: null

env:
  local:
    MONGO_ADDRS: "mongo-mongodb.mongo.svc:27017"
    MONGO_PASSWORD:
  global:
    MONGO_USER: "events_user"
    MONGO_DATABASE: "events"
    BUFFER_FLUSH_PERIOD: "30s"
    BUFFER_MIN_INSERT_EVENTS: "1"
    DEBUG: "false"
    TEXT_LOG: "true"

mongodb:
  persistence:
    enabled: false
  image:
    pullPolicy: IfNotPresent
  mongodbUsername: mongo
  mongodbDatabase: events
  # mongodbPassword: password
